dist: noble
sudo: required
language: ruby
vm:
  size: large
addons:
  chrome: stable
install: true
services:
  - docker
before_install:
  - sudo chown --recursive 1000 .
  - make docker-ci
script:
  - make tests-ci
