FROM ruby:3.4-trixie
MAINTAINER SciNote <info@scinote.net>

ARG TIKA_DIST_URL="https://archive.apache.org/dist/tika/3.2.3/tika-app-3.2.3.jar"
ENV TIKA_PATH=/usr/local/bin/tika-app.jar

# additional dependencies
# libreoffice for file preview generation
RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends postgresql-common && \
  /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y && \ 
  apt-get install -y --no-install-recommends \
  libjemalloc2 \
  libssl-dev \
  nodejs \
  postgresql-client-18 \
  default-jre-headless \
  poppler-utils \
  librsvg2-2 \
  libvips42 \
  graphviz  \
  libreoffice \
  fonts-droid-fallback \
  fonts-noto-mono \
  fonts-wqy-microhei \
  fonts-wqy-zenhei \
  libfile-mimeinfo-perl \
  chromium \
  chromium-sandbox \
  npm \
  yarnpkg && \
  wget -O $TIKA_PATH $TIKA_DIST_URL && \
  chmod +x $TIKA_PATH && \
  ln -s /usr/bin/yarnpkg /usr/bin/yarn && \
  ln -s /usr/lib/x86_64-linux-gnu/libvips.so.42 /usr/lib/x86_64-linux-gnu/libvips.so && \
  rm -rf /var/lib/apt/lists/*

ENV BUNDLE_PATH=/usr/local/bundle/

# create app directory
ENV APP_HOME=/usr/src/app
ENV PATH=$APP_HOME/bin:$PATH
RUN mkdir $APP_HOME
RUN useradd --uid 1000 -m scinote
RUN chown scinote:scinote $APP_HOME
USER scinote
WORKDIR $APP_HOME

COPY --chown=scinote:scinote . $APP_HOME

RUN bundle install --jobs `nproc`

CMD rails s -b 0.0.0.0
