// flow-typed signature: 3b2debf5c802e09acb220a975e00957c
// flow-typed version: <<STUB>>/bootstrap-sass_v^3.3.7/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-sass/assets/javascripts/bootstrap-sprockets' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/affix' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/alert' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/button' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/modal' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/popover' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/tab' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/assets/javascripts/bootstrap/transition' {
  declare module.exports: any;
}

declare module 'bootstrap-sass/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-sass/assets/javascripts/bootstrap-sprockets.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap-sprockets'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap.min'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/affix.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/affix'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/alert.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/alert'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/button.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/button'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/carousel.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/carousel'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/collapse.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/collapse'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/dropdown.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/dropdown'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/modal.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/modal'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/popover.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/popover'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/scrollspy'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/tab.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/tab'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/tooltip.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/tooltip'>;
}
declare module 'bootstrap-sass/assets/javascripts/bootstrap/transition.js' {
  declare module.exports: $Exports<'bootstrap-sass/assets/javascripts/bootstrap/transition'>;
}
declare module 'bootstrap-sass/eyeglass-exports.js' {
  declare module.exports: $Exports<'bootstrap-sass/eyeglass-exports'>;
}
