// flow-typed signature: 7b7b86fc0fad4cfbf30038772f571c29
// flow-typed version: <<STUB>>/coffee-loader_v^0.8.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffee-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffee-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'coffee-loader/index' {
  declare module.exports: $Exports<'coffee-loader'>;
}
declare module 'coffee-loader/index.js' {
  declare module.exports: $Exports<'coffee-loader'>;
}
