// flow-typed signature: 7d84dc6546c9df13320e544d946d732f
// flow-typed version: <<STUB>>/compression-webpack-plugin_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compression-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'compression-webpack-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compression-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'compression-webpack-plugin/dist/cjs'>;
}
declare module 'compression-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'compression-webpack-plugin/dist/index'>;
}
