// flow-typed signature: da68a9867b070878772bc7a5a4fa5e06
// flow-typed version: <<STUB>>/postcss-smart-import_v^0.7.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-smart-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-smart-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-smart-import/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'postcss-smart-import/lib/index.classic.commonjs' {
  declare module.exports: any;
}

declare module 'postcss-smart-import/lib/index.classic.esmodule' {
  declare module.exports: any;
}

declare module 'postcss-smart-import/lib/index.es2015.esmodule' {
  declare module.exports: any;
}

declare module 'postcss-smart-import/lib/index.modern.commonjs' {
  declare module.exports: any;
}

declare module 'postcss-smart-import/lib/index.modern.esmodule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-smart-import/gulpfile.babel.js' {
  declare module.exports: $Exports<'postcss-smart-import/gulpfile.babel'>;
}
declare module 'postcss-smart-import/lib/index.classic.commonjs.js' {
  declare module.exports: $Exports<'postcss-smart-import/lib/index.classic.commonjs'>;
}
declare module 'postcss-smart-import/lib/index.classic.esmodule.js' {
  declare module.exports: $Exports<'postcss-smart-import/lib/index.classic.esmodule'>;
}
declare module 'postcss-smart-import/lib/index.es2015.esmodule.js' {
  declare module.exports: $Exports<'postcss-smart-import/lib/index.es2015.esmodule'>;
}
declare module 'postcss-smart-import/lib/index.modern.commonjs.js' {
  declare module.exports: $Exports<'postcss-smart-import/lib/index.modern.commonjs'>;
}
declare module 'postcss-smart-import/lib/index.modern.esmodule.js' {
  declare module.exports: $Exports<'postcss-smart-import/lib/index.modern.esmodule'>;
}
