// flow-typed signature: f57a5bc4b955b3793cf046978994d263
// flow-typed version: <<STUB>>/prettysize_v^1.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettysize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettysize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prettysize/index' {
  declare module.exports: $Exports<'prettysize'>;
}
declare module 'prettysize/index.js' {
  declare module.exports: $Exports<'prettysize'>;
}
