// flow-typed signature: e3e6aeb7fce1dcbc2d7d3d2901a41adb
// flow-typed version: <<STUB>>/react-router-prop-types_v^0.0.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-prop-types/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-prop-types/dist/index.js' {
  declare module.exports: $Exports<'react-router-prop-types/dist/index'>;
}
