// flow-typed signature: e3a62462e1b024bd70ee4a18ea8c1763
// flow-typed version: <<STUB>>/react-intl-redux_v^0.6.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-redux/lib/components/IntlProvider' {
  declare module.exports: any;
}

declare module 'react-intl-redux/lib/components/Provider' {
  declare module.exports: any;
}

declare module 'react-intl-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-intl-redux/src/components/IntlProvider' {
  declare module.exports: any;
}

declare module 'react-intl-redux/src/components/Provider' {
  declare module.exports: any;
}

declare module 'react-intl-redux/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-redux/lib/components/IntlProvider.js' {
  declare module.exports: $Exports<'react-intl-redux/lib/components/IntlProvider'>;
}
declare module 'react-intl-redux/lib/components/Provider.js' {
  declare module.exports: $Exports<'react-intl-redux/lib/components/Provider'>;
}
declare module 'react-intl-redux/lib/index.js' {
  declare module.exports: $Exports<'react-intl-redux/lib/index'>;
}
declare module 'react-intl-redux/src/components/IntlProvider.js' {
  declare module.exports: $Exports<'react-intl-redux/src/components/IntlProvider'>;
}
declare module 'react-intl-redux/src/components/Provider.js' {
  declare module.exports: $Exports<'react-intl-redux/src/components/Provider'>;
}
declare module 'react-intl-redux/src/index.js' {
  declare module.exports: $Exports<'react-intl-redux/src/index'>;
}
