// flow-typed signature: 77c8c2adee8d01fa8f1e19b0a7caec65
// flow-typed version: <<STUB>>/react-timezone_v^0.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-timezone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-timezone/build/react-timezone' {
  declare module.exports: any;
}

declare module 'react-timezone/build/react-timezone.min' {
  declare module.exports: any;
}

declare module 'react-timezone/src/index' {
  declare module.exports: any;
}

declare module 'react-timezone/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-timezone/build/react-timezone.js' {
  declare module.exports: $Exports<'react-timezone/build/react-timezone'>;
}
declare module 'react-timezone/build/react-timezone.min.js' {
  declare module.exports: $Exports<'react-timezone/build/react-timezone.min'>;
}
declare module 'react-timezone/src/index.js' {
  declare module.exports: $Exports<'react-timezone/src/index'>;
}
declare module 'react-timezone/webpack.config.js' {
  declare module.exports: $Exports<'react-timezone/webpack.config'>;
}
