# Secrets
SECRET_KEY_BASE: "<<secret_key_base>>"
PAPERCLIP_HASH_SECRET: "<<paperclip_hash_secret>>"

# Mailer settings
MAIL_FROM: <scinote@epa.gov>
MAIL_REPLYTO: <scinote@epa.gov>
SMTP_ADDRESS: localhost
SMTP_PORT: 25
SMTP_DOMAIN: epa.gov
SMTP_USERNAME: gemm
SMTP_PASSWORD: gemm.gemm
MAIL_SERVER_URL: localhost

# File storage

# For local file storage
PAPERCLIP_STORAGE: "filesystem"

# For S3 file storage
#PAPERCLIP_STORAGE: "s3"
#AWS_ACCESS_KEY_ID: ""
#AWS_REGION: ""
#AWS_SECRET_ACCESS_KEY: ""
#S3_BUCKET: ""
#S3_HOST_NAME: ""

# This is needed for 'better errors' gem in development mode
TRUSTED_IP: "127.0.0.1"

# Various settings
ENABLE_TUTORIAL: "true"

NEW_TEAM_ON_SIGNUP: "true"

ENABLE_EMAIL_CONFIRMATIONS: "false"

ENABLE_RECAPTCHA: "false"
ENABLE_USER_REGISTRATION: "true"
RECAPTCHA_SITE_KEY: "<<recaptcha_site_key>>"
RECAPTCHA_SECRET_KEY: "<<recaptcha_secret_key>>"

NAVBAR_SHOW_VERSION: "false"

DELAYED_WORKER_DESTROY_FAILED_JOBS: "false"
DELAYED_WORKER_SLEEP_DELAY: "60"
DELAYED_WORKER_MAX_ATTEMPTS: "6"
DELAYED_WORKER_MAX_RUN_TIME: "30"
DELAYED_WORKER_READ_AHEAD: "10"
DELAYED_WORKER_DEFAULT_QUEUE_NAME: "default"

WOPI_ENABLED: "true"
WOPI_TEST_ENABLED: "true"
WOPI_DISCOVERY_URL: "https://ffc-onenote.officeapps.live.com/hosting/discovery"
WOPI_ENDPOINT_URL: "scinote.engineering4sustainability.com/wopi/files"
WOPI_SUBDOMAIN: "engineering4sustainability.com"
WOPI_BREADCRUMBS_HOST: "scinote.engineering4sustainability.com"

EPA_RAP_ENABLED: "true"